version: '3.0'

services:
  db:
    image: postgres:13.1-alpine
    container_name: api-fixme-db
    restart: always
    environment:
      - POSTGRES_USER=dev_fixme
      - POSTGRES_PASSWORD=password_fixme
      - POSTGRES_DB=fixme_db
    ports:
      - '5433:5432'

  api:
    build:
      context: .
    image: fixme-api
    environment:
      - DATABASE_URI=postgresql://dev_fixme:password_fixme@db:5432/fixme_db
    ports:
      - '8000:80'
    depends_on:
      - db